### PR TITLE
Fix #26: split ConstantCollector into two classes

### LINKED ISSUE #26: Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jdi/Value
(reported by Ariel, running in SMT mode.

any idea? looks like there is a mix of SMT and Dynamoth.

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jdi/Value
    at fr.inria.lille.spirals.repair.expression.factory.AccessFactory.literal(AccessFactory.java:25)
    at fr.inria.lille.spirals.repair.synthesizer.collect.spoon.ConstantCollector.process(ConstantCollector.java:78)
    at fr.inria.lille.spirals.repair.synthesizer.collect.spoon.ConstantCollector.process(ConstantCollector.java:18)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:92)
    at spoon.reflect.visitor.CtScanner.visitCtBinaryOperator(CtScanner.java:266)
    at spoon.support.reflect.code.CtBinaryOperatorImpl.accept(CtBinaryOperatorImpl.java:35)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.reflect.visitor.CtScanner.visitCtFor(CtScanner.java:417)
    at spoon.support.reflect.code.CtForImpl.accept(CtForImpl.java:44)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
    at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:273)
    at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.reflect.visitor.CtScanner.visitCtFor(CtScanner.java:419)
    at spoon.support.reflect.code.CtForImpl.accept(CtForImpl.java:44)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
    at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:273)
    at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:46)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.reflect.visitor.CtScanner.visitCtMethod(CtScanner.java:508)
    at spoon.support.reflect.declaration.CtMethodImpl.accept(CtMethodImpl.java:58)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:64)
    at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:309)
    at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
    at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:145)
    at spoon.support.visitor.ProcessingVisitor.scan(ProcessingVisitor.java:88)
    at spoon.support.RuntimeProcessingManager.process(RuntimeProcessingManager.java:145)
    at spoon.support.RuntimeProcessingManager.process(RuntimeProcessingManager.java:133)
    at fr.inria.lille.commons.spoon.SpoonedFile.processModelledClasses(SpoonedFile.java:136)
    at fr.inria.lille.commons.spoon.SpoonedFile.process(SpoonedFile.java:128)
    at fr.inria.lille.commons.spoon.SpoonedFile.process(SpoonedFile.java:124)
    at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:94)
    at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:183)
    at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:117)
    at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:82)
    at fr.inria.lille.repair.Main.main(Main.java:63)

### PR DESCRIPTION
**Pull request by danglotb**

### CODE REVIEW

File: nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+import spoon.reflect.code.CtThrow;
+import spoon.reflect.declaration.CtElement;
+import spoon.reflect.declaration.CtField;
+import spoon.reflect.declaration.CtMethod;
+
+/**
+ * Created by bdanglot on 10/4/16.
+ */
+public class DefaultConstantCollector extends AbstractProcessor<CtLiteral> {
+
```
Comment (danglotb) [inline nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java:13]: This class has no impact on the state of the program (contain only some checks and return statement). We should just remove it IMHO.

Comment (monperrus) [reply nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java:13]: We collect all literals by default also in SMT mode.

File: nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+		this.constants = constants;
+		//default constants
+		constants.put("-1", -1);
+		constants.put("0", 0);
+		constants.put("1", 1);
+	}
+
+	@Override
+	public boolean isToBeProcessed(CtLiteral candidate) {
+		CtMethod parent = candidate.getParent(CtMethod.class);
```
Comment (monperrus) [inline nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java]: we don't care about the parent, remove the tests

File: nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+		if (parent == null) {
+			return false;
+		}
+
+		if (candidate.getValue() instanceof Boolean) {
+			return false;
+		} else if (candidate.getValue() instanceof Number) {// 3 defaults value will be added anyway
+			if (candidate.getValue().equals(1) ||
```
Comment (monperrus) [inline nopol/src/main/java/fr/inria/lille/spirals/repair/synthesizer/collect/spoon/DefaultConstantCollector.java]: remove
