### PR TITLE
Fix #35: consitency spec and logs

### LINKED ISSUE #35: confusing log?
from Ariel

Analysing introclassJava.median_90a14c1a_000{exec()V[69:69 0.5773502691896258
Failing test(s): SourceLocation introclassJava.median_90a14c1a_000:69
    [WB 3]
First set: 
    [WB 3]
Second set: 
    [WB 4, WB 3, WB 1, BB 7]
1 input values set(s). There are not enough tests for SourceLocation introclassJava.median_90a14c1a_000:69 otherwise the patch would be "true" or "false"
Could not find a patch in introclassJava.median_90a14c1a_000{exec()V[69:69 0.5773502691896258

this statement (69) evaluates to false for all failing tests, and making it true would work for 3 out of 4 failing tests, so I think this case should be tagged as "Changing only this statement does not solve the bug" (the test WB 3 fails no matter the angelic value used on statement 69)

are there really 4 executions of this line?

### PR DESCRIPTION
**Pull request by danglotb**
Improvement of the consistency specifications management. We identify 3 cases:

> case 1: inconsistent specs (same keys, different outcomes): if condition can be flipped, it has no impact, so discarded
> case 2: different input, same output: malformed problems, only the first key set kept.
> case 3: same inputs and same output: redundant tests, discarded.

For each case, a log has been added.

More over, with the fix of consistency, NoPol is able to find a patch for median_90a14c1a from IntroClassJava while it could not before.

### CODE REVIEW

File: nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java [hunk 1]
```diff
@@ -8,79 +10,103 @@
...
+		}
+
+		if (reference == null && this.keys.equals(inputs.keySet())) {
+			// no such spec so far
+			consistentInputs().put(inputs, output);
+			return;
+		}
+
+		if (output.equals(reference) && this.keys.equals(inputs.keySet())) {
+			this.logger.warn("You may have some redundant test: same input and same outcome, only one will be used: discarded.");// case 3
```
Comment (monperrus) [inline nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java]: in each log line can you add the specification as well?

File: nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java [hunk 2]
```diff
@@ -8,79 +10,103 @@
...
+			// already there, we don't duplicate the specification line which would slow SMT afterwards
+			return;
+		}
+
+		// here we have two different outcomes for the same input value
+		// it's a logical contradiction
+		// we discard it
+		this.inconsistentInputs.add(inputs);
+		if (!this.keys.equals(inputs.keySet())) {
+			this.logger.debug("Malformed problems: the same input value has different outcome: discarded.");// case 2
```
Comment (monperrus) [inline nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java]: Message should be "Ill-formed problem: not  the input variables in "+inputs +" reference ("+keys+")"

File: nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java [hunk 3]
```diff
@@ -8,79 +10,103 @@
...
+			consistentInputs().remove(inputs);
+		} else {
+			this.logger.debug("Inconsistent specification: same input with same outcome, the condition can be flipped with no impact: discarded.");// case 1
```
Comment (monperrus) [inline nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java]: same input with different outcome, logical contradiction, discarding the second one.

File: nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java [hunk 4]
```diff
@@ -67,7 +67,8 @@ private void addToSpec(Map<String, Object> inputs, T output) {
 		}
 
 		if (output.equals(reference) && this.keys.equals(inputs.keySet())) {
-			this.logger.warn("You may have some redundant test: same input and same outcome, only one will be used: discarded.");// case 3
```
Comment (monperrus) [inline nopol/src/main/java/fr/inria/lille/commons/trace/SpecificationTestCasesListener.java]: you have redundant tests:  same input and same outcome, only one will be used to speed-up synthesis

**Comment by monperrus** [comment]
the new tests are really good!
